package com.manikandan.expensetracker.ui.theme

import androidx.compose.ui.unit.dp

val EXTRA_LARGE_PADDING = 40.dp
val LARGER_PADDING = 25.dp
val LARGE_PADDING = 20.dp
val MEDIUM_PADDING = 16.dp
val SMALL_PADDING = 10.dp
val EXTRA_SMALL_PADDING = 6.dp

val PAGER_INDICATOR_WIDTH = 12.dp
val PAGER_INDICATOR_SPACING = 8.dp

val TRANSACTION_TITLE_PLACE_HOLDER_HEIGHT = 30.dp
val TRANSACTION_MONTH_YEAR_PLACE_HOLDER_HEIGHT = 20.dp
val RECENT_TRANSACTIONS_SINGLE_ITEM_PLACE_HOLDER_HEIGHT = 60.dp